name: Generate API docs

on:
  push:
    branches:
      - main
  pull_request: # for testing
  release:
    types: [published]

jobs:
  halo_api_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
